### ISSUE TITLE
License Problems

### ISSUE THREAD

**Issue by jbk123456** [belgattitude/php-java-bridge#16]
Hi,

README.md states that you distribute your code under the MIT license.

However, your source code contains at least two files (PhpDebugger.php and PhpDebugger.inc) which are covered by the GUILE (GPL+CP exception) License.

Please either change the license to GPL or remove those files.

**Comment by belgattitude** [comment]
Hi Jost,

Thanks a lot for pointing out. 

I've tried to put the pieces together about licences in #10, you can have a look. But I'm aware that I need more time to read all files. It's just more a timing issue that I'll solve before releasing new version. Just need to start somewhere.

I'll keep you informed during the week. As my time is limited, I'll probably drop everything that is not MIT (or at least compatible). Note that I don't have a definitive point of view about license, so everything is open. Feel free to comment.

I'm also very happy to have your contact, tried to mail you and other authors from sourforge profile without success. 

Just want to let you know, that It means a lot to me to respect your work. So If you feel things must be done in a different way, a feel something is wrong regarding the fork, credits... please contact me.

 And thanks again

**Comment by belgattitude** [comment]
For now I removed the PHPDebugger.inc and PHPDebugger.php files as well ad the 'unsupported' directory.

I found out the [launcher.c](https://github.com/belgattitude/php-java-bridge/blob/master/src/main/webapp/WEB-INF/cgi/launcher.c) is also GPL. As you are the author, could you tell me what is your position about it ? And would you agree to update licensing to MIT ?

Sorry if the question is not appropriate or could be badly taken... it's not my intention. But good to know you point of view. And feel free also to give me directions how you feel with the fork or the way it's done.

Thanks a lot.

**Comment by jbk123456** [comment]
Hi Sebastien,

the license already allows you to write proprietary software and link it to the php/java bridge. 

Why exactly do you want me to change it?

**Comment by belgattitude** [comment]
Hi Jost,

Absolutely right, I haven't read to the end. So looks good to me, thank you. 

*FYI, I moved the launcher.c to the ./legacy folder to avoid collision of licences in main sources.*

**Comment by belgattitude** [comment]
Hi Jost,

Just realized that the build of [Java.inc](https://github.com/belgattitude/php-java-bridge/tree/master/src/main/webapp/java) is MIT while its [originating files](https://github.com/belgattitude/php-java-bridge/tree/master/legacy/server/META-INF/java) are stating GPL (with the same commercial exception as launcher.c)

*Not a problem as those files are not build anymore and stored in the './legacy' folder. But just wanted to be sure in order to close #10.*

But when I started to [refactor the client](https://github.com/belgattitude/soluble-japha/blob/master/doc/notes.md#differences-with-the-legacy-javainc-client), I started from the Java.inc file stating MIT as well as this [thread](https://sourceforge.net/p/php-java-bridge/mailman/message/22988622/). and so published the code under MIT accordingly. Looking at the [license headers afterwards](https://github.com/belgattitude/soluble-japha/tree/master/src/Soluble/Japha/Bridge/Driver/Pjb62), I realized I didn't include your name, but I suppose keeping MIT is your intention ? At least I'll update credits asap.

It's an 'only free time' project with no commercial expectations. But in the short term, I'd like to provide an 'easy-to-setup' infrastructure to build some php/java libs (like JasperReports...), having clear license is also part of it.

**Comment by belgattitude** [comment]
Just updated to credits and license header of the refactored soluble-japha client.

- https://github.com/belgattitude/soluble-japha/issues/33
- https://github.com/belgattitude/soluble-japha/commit/1de217396ed7e02a6a7a0bc3b31e6374568f0602

**Comment by belgattitude** [comment]
Hi @jbk123456 ,

Just open a ticket #47 to see about upstream policy... I have the impression the the fork might have created some frictions. I hope I'm wrong and maybe we can create some kind of convergence... 

Feel free to contact me directly -> sebastien [at] nuvolia.com. My english is not always perfect but I would be very happy to answer all your questions
