### ISSUE TITLE
Support for javax.servlet:javax.servlet-api:3.1.0

### ISSUE THREAD

**Issue by belgattitude** [belgattitude/php-java-bridge#25]
Current release 6.2.11 run under servlet api 2.5 and 3.0.1 specs... 

Can be a nice addition to refactor the code to support the 3.1.0 as well

In order to test, update the gradle providedCompile section with

```
providedCompile('javax.servlet:javax.servlet-api:3.0.1')
```

Currently this gives this error:

```

/path/php-java-bridge/src/main/java/io/soluble/pjb/servlet/RemoteHttpServletResponse.java:69: error: <anonymous io.soluble.pjb.servlet.RemoteHttpServletResponse$1> is not abstract and does not override abstract method setWriteListener(WriteListener) in ServletOutputStream
        return out = new ServletOutputStream() {
                                               ^
/path/php-java-bridge/src/main/java/io/soluble/pjb/servlet/VoidInputHttpServletRequest.java:29: error: <anonymous io.soluble.pjb.servlet.VoidInputHttpServletRequest$1> is not abstract and does not override abstract method setReadListener(ReadListener) in ServletInputStream
        return in = new ServletInputStream() {

```

**Comment by cplerch** [comment]
Well, my take on this issue is: the higher is not the better.
You can view it ths way: The version of the servlet api is a statement of
the webapp about the requirements it has to the servlet container, not the
other way around. It means, that if your webapp only requires v2.5 services
from the container it should not act like a poseur and specify more. Thus I
suggest to go back to v2.5
This will not prevent the webapp to run on the most recent conatiner
versions (they are always strictly backwards compatible), while it broadens
the users choice: he can run it e.g. on any tomcat from v6 to v9.
See: http://tomcat.apache.org/whichversion.html
Best,
Chris

2017-02-11 17:37 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by belgattitude** [comment]
Hi @cplerch, that's a good point. So I close it.

Thanks
